//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renda
    {
        public int id { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<double> valor { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
