//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoObjeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoObjeto()
        {
            this.Objeto = new HashSet<Objeto>();
        }
    
        public int id { get; set; }
        public Nullable<int> usuario_id { get; set; }
        public string nome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Objeto> Objeto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
